### ISSUE TITLE
sample data for running the program

### ISSUE THREAD

**Issue by liziliao** [marcbelmont/hierarchical-categories-loss-tensorflow#1]
Hi, thank you for sharing your code here. Would you please give a sample data set for running the code? For example, the 'cache/allrecipes-info.json' and 'data/recipes*.jl'. There are many terms inside which are hard to guess the meaning without sample data.

**Comment by marcbelmont** [comment]
Here you go. The sample data + instructions should help you get started. I hope it helps. What project are you working on?

**Comment by liziliao** [comment]
Thank you very much! I am working on general hierarchical loss
implementation.

Marc Belmont <notifications@github.com> 于2018年9月27日周四 上午9:47写道：

**Comment by marcbelmont** [comment]
That's great. I'd love to see what you end up doing.
